"use strict";
/**
 * Seed data for students and alumni
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ALUMNI_SEED_DATA = exports.STUDENT_SEED_DATA = void 0;
exports.STUDENT_SEED_DATA = [
    {
        name: 'Kashish Kumar',
        email: 'kashish@ldce.ac.in',
        role: 'student',
        password: 'password123',
        year: '3rd Year',
        branch: 'Computer Science',
        skills: ['JavaScript', 'React', 'Node.js', 'MongoDB'],
        interests: ['Web Development', 'AI', 'Open Source'],
        projects: ['E-commerce App', 'Chat Application', 'Portfolio Website'],
        bio: 'Passionate developer interested in full-stack development',
    },
    {
        name: 'Priya Sharma',
        email: 'priya@ldce.ac.in',
        role: 'student',
        password: 'password123',
        year: '2nd Year',
        branch: 'Information Technology',
        skills: ['Python', 'Data Science', 'Machine Learning', 'SQL'],
        interests: ['Machine Learning', 'Data Analytics', 'Cloud Computing'],
        projects: ['Predictive Analytics', 'Recommendation System'],
        bio: 'Data science enthusiast with passion for solving real-world problems',
    },
    {
        name: 'Arjun Patel',
        email: 'arjun@ldce.ac.in',
        role: 'student',
        password: 'password123',
        year: '3rd Year',
        branch: 'Computer Science',
        skills: ['Java', 'Spring Boot', 'AWS', 'Docker'],
        interests: ['Backend Development', 'DevOps', 'Microservices'],
        projects: ['Distributed Payment System', 'Cloud Infrastructure'],
        bio: 'Backend engineer focused on scalable architecture',
    },
    {
        name: 'Neha Verma',
        email: 'neha@ldce.ac.in',
        role: 'student',
        password: 'password123',
        year: '1st Year',
        branch: 'Electronics & Communication',
        skills: ['C++', 'Python', 'IoT', 'Embedded Systems'],
        interests: ['IoT', 'Robotics', 'Embedded Systems'],
        projects: ['Smart Home System', 'IoT Weather Station'],
        bio: 'IoT enthusiast working on smart device solutions',
    },
    {
        name: 'Rohan Singh',
        email: 'rohan@ldce.ac.in',
        role: 'student',
        password: 'password123',
        year: '2nd Year',
        branch: 'Computer Science',
        skills: ['React', 'Vue.js', 'CSS', 'UI/UX Design'],
        interests: ['Frontend Development', 'UI/UX Design', 'Web Design'],
        projects: ['Design System', 'SaaS Dashboard', 'Mobile App UI'],
        bio: 'Frontend developer passionate about creating beautiful user interfaces',
    },
];
exports.ALUMNI_SEED_DATA = [
    {
        name: 'Rahul Desai',
        email: 'rahul@ldce.ac.in',
        role: 'alumni',
        password: 'password123',
        company: 'Google India',
        position: 'Senior Software Engineer',
        domain: 'Cloud & Infrastructure',
        yearsOfExperience: 5,
        availability: 'Open',
        capabilities: ['System Design', 'Cloud Architecture', 'Team Leadership'],
        bio: 'Senior engineer at Google with expertise in distributed systems',
        linkedinUrl: 'https://linkedin.com/in/rahul-desai',
        githubUrl: 'https://github.com/rahul-desai',
    },
    {
        name: 'Anjali Gupta',
        email: 'anjali@ldce.ac.in',
        role: 'alumni',
        password: 'password123',
        company: 'Microsoft',
        position: 'Product Manager',
        domain: 'Product Management',
        yearsOfExperience: 4,
        availability: 'Limited',
        capabilities: ['Product Strategy', 'User Research', 'Analytics'],
        bio: 'Product Manager at Microsoft building cloud solutions',
        linkedinUrl: 'https://linkedin.com/in/anjali-gupta',
    },
    {
        name: 'Vikram Sharma',
        email: 'vikram@ldce.ac.in',
        role: 'alumni',
        password: 'password123',
        company: 'Startup XYZ',
        position: 'CTO & Co-founder',
        domain: 'Entrepreneurship',
        yearsOfExperience: 3,
        availability: 'Busy',
        capabilities: ['Startup Building', 'Technical Leadership', 'Fundraising'],
        bio: 'Startup founder building the next generation of SaaS tools',
        linkedinUrl: 'https://linkedin.com/in/vikram-sharma',
        githubUrl: 'https://github.com/vikram-sharma',
        personalWebsite: 'https://vikram-sharma.dev',
    },
    {
        name: 'Divya Patel',
        email: 'divya@ldce.ac.in',
        role: 'alumni',
        password: 'password123',
        company: 'Amazon',
        position: 'Senior Data Scientist',
        domain: 'Machine Learning',
        yearsOfExperience: 6,
        availability: 'Limited',
        capabilities: ['Machine Learning', 'Big Data', 'Statistical Analysis'],
        bio: 'Data scientist at Amazon working on recommendation engines',
        linkedinUrl: 'https://linkedin.com/in/divya-patel',
        githubUrl: 'https://github.com/divya-patel',
    },
];
//# sourceMappingURL=seedData.js.map